### ISSUE TITLE
მძღოლის ადგილმდებარეობის შესაყვანი გრაფიკული ინტერფეისი ოპერატორისთვის

### ISSUE THREAD

**Issue by vmaskhulia** [freeuni-sdp/FreeUni-SDP-2014-Final-Project#21]
ზოგადად გამართული იქნება ოპერატორისთვის განკუთვნილი გრაფიკული ინტერფეისი (მისი ჩონჩხი).

ძირითადი აქცენტი გაკეთდება მძღოლის ადგილმდებარეობის შეყვანაზე. ოპერატორისთვის გამოტანილი იქნება ცხრილი სადაც ნაჩვენები იქნება მძღოლის ადგილსამყოფელი და დრო, როდესაც უკანასკნელად მოხდა ამ ინფორმაციის განახლება. დროს დათვლა უნდა მოხდეს სერვერზე.
ჯერჯერობით ამისთვის საჭიროა 2 ფუნქციონალი კლიენტისთვის სერვერისგან:
- მძღოლების და მათი ადგილმდებარეობის შესახებ ინფორმაციის ამოღება.

ამისთვის უნდა მოხდეს GET-ის საშუალებით '/api/drivers' ლინკის გამოძახება და პასუხად სერვერისგან უნდა მივიღოთ შემდეგი ფორმატი:
[
    { "name": "driverone", "location": {
      "name":"Kandelaki Street", "last_update": "date" } },
    { "name": "drivertwo", "location": {
      "name": "Budapest Street #13a", "last_update": "date" } }
]...
JSON-ის, მასივი სადაც გვაქვს ინფორმაცია მძღოლის სახელზე, ადგილმდებარეობასა და განახლების დროზე. დრო (ამ შემთხვევაში date) არის თარიღის timestamp-ი.
დიდი ალბათობით საჭირო გახდება ამ ფორმატის შეცვლა, მაგრამ კონკრეტული ამოცანისთვის ჩემი აზრით საკმარისია.
- მძღოლის ადგილმდებარეობის განახლება.

ამ შემთხვევაში PUT-ით უნდა მოხდეს გამოძახება '/api/drivers/' + მძღოლის სახელი.
დამატებით სერვერს უნდა გადაეცემოდეს მძღოლის ობიექტი
მაგ. { "name": "driverfour", "location": { "name": "Budapest Street #13a" } }.
პასუხად ჩემს შემთხვევაში ვაბრუნებ განახლებულ მძღოლების მთლიან სიას სიმარტივისთვის.

ტექნოლოგიები: 
მოდული დაიწერება ვებ-ში, ჯავასკრიპტის ფრეიმვორკი - angularjs. ფრეიმვორკი გრაფიკისთვის - bootstrap (აქვს dependency jquery-ზე). 
ამ ბიბლიოთეკების დასაინკლუდებლად გამოყებული იქნება bower.

**Comment by sdolidze** [comment]
ზევით რაც გიწერია არ არის JSON-ი :P ჯავასკპრიპტის ობიექტია :)

**Comment by vmaskhulia** [comment]
გავასწორე, ამჯერად ონლაინ პარსერში შევამოწმე oO
